version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
            - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
        container_name: sale_real_property_web
        ports:
            - "8888:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        container_name: sale_real_property_app
        volumes:
            - ../:/var/www
        links:
            - database
        environment:
            - DB_PORT=3306
            - DB_HOST=database
    database:
        image: mysql:5.7.25
        container_name: sale_real_property_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=sale_real_property
        ports:
            - 33061:3306
        volumes:
            - ebay-db:/var/lib/mysql
volumes:
  ebay-db:
